name:                boolean-algebra
version:             0.1.0.0
github:              "xicesky/boolean-algebra"
license:             BSD3
author:              "Markus Dangl"
maintainer:          "sky@q1cc.net"
copyright:           "(c) 2021 Markus Dangl"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/xicesky/boolean-algebra#readme>

dependencies:
- base >= 4.7 && < 5
- data-fix
- mtl
- transformers
- compdata
- tree-view
- deriving-compat
- hashable
- containers
- unordered-containers
- sky-utils
- criterion
- QuickCheck

default-extensions:
- ConstraintKinds
- DataKinds
- DeriveFunctor
- EmptyDataDecls
- FlexibleContexts
- FlexibleInstances
- GADTs
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NoStarIsType
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneKindSignatures
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators

library:
  source-dirs: src

executables:
  boolean-algebra-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - boolean-algebra

tests:
  boolean-algebra-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - boolean-algebra
    - QuickCheck
    - hspec
    - quickcheck-instances
